document.addEventListener('DOMContentLoaded',function(){
const open=document.getElementById('open'),site=document.getElementById('site');
document.getElementById('openBtn').onclick=function(){site.classList.add('show');open.classList.add('hide');document.body.classList.remove('locked');setTimeout(()=>open.style.display='none',750)};
const target=new Date('2026-11-23T10:00:00+05:30').getTime();
function tick(){let d=Math.max(0,target-Date.now());document.getElementById('days').textContent=String(Math.floor(d/86400000)).padStart(2,'0');document.getElementById('hours').textContent=String(Math.floor(d/3600000)%24).padStart(2,'0');document.getElementById('mins').textContent=String(Math.floor(d/60000)%60).padStart(2,'0');document.getElementById('secs').textContent=String(Math.floor(d/1000)%60).padStart(2,'0')}tick();setInterval(tick,1000);
const c=document.getElementById('scratchCanvas'),x=c.getContext('2d');let down=false,done=false;
function size(){let r=c.getBoundingClientRect(),p=devicePixelRatio||1;c.width=r.width*p;c.height=r.height*p;x.setTransform(p,0,0,p,0,0);x.fillStyle='#286b70';x.fillRect(0,0,r.width,r.height);x.fillStyle='#fff6e8';x.textAlign='center';x.font='600 14px Montserrat';x.fillText('SCRATCH HERE',r.width/2,r.height/2);x.font='400 10px Montserrat';x.fillText('Reveal our special day',r.width/2,r.height/2+20)}size();addEventListener('resize',size);
function scratch(e){if(done)return;let r=c.getBoundingClientRect();x.globalCompositeOperation='destination-out';x.beginPath();x.arc(e.clientX-r.left,e.clientY-r.top,25,0,Math.PI*2);x.fill();let a=x.getImageData(0,0,c.width,c.height).data,n=0,s=0;for(let i=3;i<a.length;i+=80){s++;if(a[i]<30)n++}if(n/s>.34){done=true;c.style.opacity=0;c.style.pointerEvents='none'}}
c.onpointerdown=e=>{down=true;c.setPointerCapture?.(e.pointerId);scratch(e)};c.onpointermove=e=>{if(down)scratch(e)};c.onpointerup=()=>down=false;c.onpointercancel=()=>down=false;
document.getElementById('calendar').onclick=function(){let s=new Date('2026-11-23T10:00:00+05:30'),e=new Date(s.getTime()+7200000),f=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');let ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//D and S Wedding//EN','BEGIN:VEVENT','DTSTART:'+f(s),'DTEND:'+f(e),'SUMMARY:Wedding of Dr. Salivendra Deevena & Dr. Manukonda Sasi Preetham','LOCATION:Adabala Gardens, Saibaba Temple Rd, Palakollu, Andhra Pradesh 534260','END:VEVENT','END:VCALENDAR'].join('\r\n');let u=URL.createObjectURL(new Blob([ics],{type:'text/calendar'})),a=document.createElement('a');a.href=u;a.download='D-and-S-Wedding.ics';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
});